server:
  port: 80
#微信相关数据
wechat:
  develop:
    token: 自己的token
    app_id: 自己的app_id
    app_secret: 自己的app_secret
    encoding_AESKey: 自己的encoding_AESKey
    get_access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential
ai:
  develop:
    ai_key: ai_key
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 1
    # 连接超时时间（毫秒）
    timeout: 10000
    password: 自己的password
logging:
  level:
    com.zjh.wxchat: trace
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 20
      # 配置队列大小
      queue_capacity: 999
      name:
        prefix: async-service-
proxy:
  host: 127.0.0.1
  port: 7890